FROM postgres:15

ENV POSTGRES_USER=devpodcasts
ENV POSTGRES_PASSWORD=password123
ENV POSTGRES_DB=devpodcasts

EXPOSE 5432

# Opcjonalnie - dodaj custom initialization scripts
 COPY init.sql /docker-entrypoint-initdb.d/

