  version: '3.8'

  services:
    postgres:
      build:
        context: .
        dockerfile: Dockerfile.postgres
      container_name: devpodcasts-postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=devpodcasts
        - POSTGRES_PASSWORD=password123
        - POSTGRES_DB=devpodcasts
      volumes:
        - postgres_data:/var/lib/postgresql/data
      restart: unless-stopped
    
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4
      restart: unless-stopped
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - postgres

  volumes:
    postgres_data:

